### PR TITLE
Changed English verbiage and 'About' text/links

### PR DESCRIPTION
**Pull request by randypower**
- Improved English translation of preferences and strings in UI
- Updated 'About' with new website URLs for osmo.mobi (was osmodroid.com)
- Removed "Manual monitoring: http://esya.ru/om/start/" (because I did not find a new URL to link to)

Signed-off-by: Randy Schnedler randypower@oscar.local

### CODE REVIEW

**Comment by randypower** [comment]
Hello!  This is 'schnedlr@yahoo.com'.  This is my first time doing a pull request in git/github.  Please let me know if I did it correctly.

-Randy

**Comment by GaMsh** [comment]
Oh =( Wrong branch of code

**Comment by randypower** [comment]
Oh no! What branch should I have used?  How can I fix it? Would you prefer that I email the changed files to you?

**Comment by GaMsh** [comment]
Please wait, I relocated the code and try to move your changes

**Comment by randypower** [comment]
OK

**Comment by GaMsh** [comment]
We have move it https://github.com/OpenStreetMap-Monitoring/OsMoDroid/commit/78f11b9450cdd2da0780c5550eddc9c823b329cf

**Comment by randypower** [comment]
Thank you. I'm sorry I started in the wrong place. I will fix that for next time.

It feels good to contribute to your project and open source again.

Randy

**Pull request merged**
